### ISSUE TITLE
Configuração do VENV em projetos DJango.

### ISSUE THREAD

**Issue by phmiranda** [alura-cursos/alura_receitas_django#1]
Bom dia @guilhermeonrails , gostaria de tirar uma dúvida. Ao enviar os projetos python para um repositório remoto, é recomendado adicionar ao .gitignore o diretório VENV ou não ? Já que se trata de configurações locais do ambiente.

**Comment by guilhermeonrails** [comment]
Fala Pedro, bom dia

Exatamente. Não é necessário enviar a venv para um repositório remoto.
Recomendo que execute o pip freeze > requirements.txt para o repositorio,
listando as libs e módulos do projeto.

*:)*
*Att, *
*Guilherme Lima*



Em sáb., 22 de ago. de 2020 às 21:54, Pedro Henrique <
notifications@github.com> escreveu:

**Comment by phmiranda** [comment]
Massa @guilhermeonrails , estou vendo seus cursos na Alura sobre DJango e irei fazer isso ai que falou sobre o freeze.

**Comment by guilhermeonrails** [comment]
Combinado Pedro.

Bons estudos!!!

*:)*
*Att, *
*Guilherme Lima*



Em seg., 24 de ago. de 2020 às 09:57, Pedro Henrique <
notifications@github.com> escreveu:
